export const images = [
  {
    args: ['/test.png', {}],
    ipx: { url: '/_ipx/_/test.png' },
    cloudflare: { url: '/test.png' },
    cloudinary: { url: '/f_auto,q_auto/test' },
    directus: { url: '/assets/test.png' },
    twicpics: { url: '/test.png' },
    fastly: { url: '/test.png' },
    glide: { url: '/test.png' },
    gumlet: { url: '/test.png' },
    imgix: { url: '/test.png' },
    imageengine: { url: '/test.png' },
    unsplash: { url: '/test.png' },
    imagekit: { url: '/test.png' },
    netlify: { url: '/test.png' },
    prismic: { url: '/test.png?auto=compress,format&rect=0,0,200,200&w=100&h=100' },
    sanity: { url: 'https://cdn.sanity.io/images/projectid/production/test-300x450.png?auto=format' },
    contentful: { url: '/test.png' },
    cloudimage: { url: 'https://demo.cloudimg.io/v7/test.png' }
  },
  {
    args: ['/test.png', { width: 200 }],
    ipx: { url: '/_ipx/w_200/test.png' },
    cloudflare: { url: '/cdn-cgi/image/w=200/test.png' },
    cloudinary: { url: '/f_auto,q_auto,w_200/test' },
    directus: { url: '/assets/test.png?width=200' },
    twicpics: { url: '/test.png?twic=v1/cover=200x-' },
    fastly: { url: '/test.png?width=200' },
    glide: { url: '/test.png?w=200' },
    gumlet: { url: '/test.png?w=200' },
    imgix: { url: '/test.png?w=200' },
    imageengine: { url: '/test.png?imgeng=/w_200' },
    unsplash: { url: '/test.png?w=200' },
    imagekit: { url: '/test.png?tr=w-200' },
    netlify: { url: '/test.png?w=200&nf_resize=fit' },
    prismic: { url: '/test.png?auto=compress,format&rect=0,0,200,200&w=200&h=100' },
    sanity: { url: 'https://cdn.sanity.io/images/projectid/production/test-300x450.png?w=200&auto=format' },
    contentful: { url: '/test.png?w=200' },
    cloudimage: { url: 'https://demo.cloudimg.io/v7/test.png?width=200' }
  },
  {
    args: ['/test.png', { height: 200 }],
    ipx: { url: '/_ipx/h_200/test.png' },
    cloudflare: { url: '/cdn-cgi/image/h=200/test.png' },
    cloudinary: { url: '/f_auto,q_auto,h_200/test' },
    directus: { url: '/assets/test.png?height=200' },
    twicpics: { url: '/test.png?twic=v1/cover=-x200' },
    fastly: { url: '/test.png?height=200' },
    glide: { url: '/test.png?h=200' },
    gumlet: { url: '/test.png?h=200' },
    imgix: { url: '/test.png?h=200' },
    imageengine: { url: '/test.png?imgeng=/h_200' },
    unsplash: { url: '/test.png?h=200' },
    imagekit: { url: '/test.png?tr=h-200' },
    netlify: { url: '/test.png?h=200&nf_resize=fit' },
    prismic: { url: '/test.png?auto=compress,format&rect=0,0,200,200&w=100&h=200' },
    sanity: { url: 'https://cdn.sanity.io/images/projectid/production/test-300x450.png?h=200&auto=format' },
    contentful: { url: '/test.png?h=200' },
    cloudimage: { url: 'https://demo.cloudimg.io/v7/test.png?height=200' }
  },
  {
    args: ['/test.png', { width: 200, height: 200 }],
    ipx: { url: '/_ipx/s_200x200/test.png' },
    cloudflare: { url: '/cdn-cgi/image/w=200,h=200/test.png' },
    cloudinary: { url: '/f_auto,q_auto,w_200,h_200/test' },
    directus: { url: '/assets/test.png?width=200&height=200' },
    twicpics: { url: '/test.png?twic=v1/cover=200x200' },
    fastly: { url: '/test.png?width=200&height=200' },
    glide: { url: '/test.png?w=200&h=200' },
    gumlet: { url: '/test.png?w=200&h=200' },
    imgix: { url: '/test.png?w=200&h=200' },
    imageengine: { url: '/test.png?imgeng=/w_200/h_200' },
    unsplash: { url: '/test.png?w=200&h=200' },
    imagekit: { url: '/test.png?tr=w-200,h-200' },
    netlify: { url: '/test.png?w=200&h=200&nf_resize=fit' },
    prismic: { url: '/test.png?auto=compress,format&rect=0,0,200,200&w=200&h=200' },
    sanity: { url: 'https://cdn.sanity.io/images/projectid/production/test-300x450.png?w=200&h=200&auto=format' },
    contentful: { url: '/test.png?w=200&h=200' },
    cloudimage: { url: 'https://demo.cloudimg.io/v7/test.png?width=200&height=200' }
  },
  {
    args: ['/test.png', { width: 200, height: 200, fit: 'contain' }],
    ipx: { url: '/_ipx/fit_contain,s_200x200/test.png' },
    cloudflare: { url: '/cdn-cgi/image/w=200,h=200,fit=contain/test.png' },
    cloudinary: { url: '/f_auto,q_auto,w_200,h_200,c_scale/test' },
    directus: { url: '/assets/test.png?width=200&height=200&fit=contain' },
    twicpics: { url: '/test.png?twic=v1/inside=200x200' },
    fastly: { url: '/test.png?width=200&height=200&fit=bounds' },
    glide: { url: '/test.png?w=200&h=200&fit=contain' },
    gumlet: { url: '/test.png?w=200&h=200&fit=fill' },
    imgix: { url: '/test.png?w=200&h=200&fit=fill' },
    imageengine: { url: '/test.png?imgeng=/w_200/h_200/m_letterbox' },
    unsplash: { url: '/test.png?w=200&h=200&fit=fill' },
    imagekit: { url: '/test.png?tr=w-200,h-200,cm-pad_resize' },
    netlify: { url: '/test.png?w=200&h=200&nf_resize=fit' },
    prismic: { url: '/test.png?auto=compress,format&rect=0,0,200,200&w=200&h=200&fit=fill' },
    sanity: { url: 'https://cdn.sanity.io/images/projectid/production/test-300x450.png?w=200&h=200&fit=fill&auto=format&bg=ffffff' },
    contentful: { url: '/test.png?w=200&h=200&fit=fill' },
    cloudimage: { url: 'https://demo.cloudimg.io/v7/test.png?width=200&height=200&func=fit' }
  },
  {
    args: ['/test.png', { width: 200, height: 200, fit: 'contain', format: 'jpeg' }],
    ipx: { url: '/_ipx/fit_contain,f_jpeg,s_200x200/test.png' },
    cloudflare: { url: '/cdn-cgi/image/w=200,h=200,fit=contain,f=jpeg/test.png' },
    cloudinary: { url: '/f_jpg,q_auto,w_200,h_200,c_scale/test' },
    directus: { url: '/assets/test.png?width=200&height=200&fit=contain&format=jpg' },
    twicpics: { url: '/test.png?twic=v1/output=jpeg/inside=200x200' },
    fastly: { url: '/test.png?width=200&height=200&fit=bounds&format=jpeg' },
    glide: { url: '/test.png?w=200&h=200&fit=contain&fm=jpeg' },
    gumlet: { url: '/test.png?w=200&h=200&fit=fill&format=jpeg' },
    imgix: { url: '/test.png?w=200&h=200&fit=fill&fm=jpeg' },
    imageengine: { url: '/test.png?imgeng=/w_200/h_200/m_letterbox/f_jpg' },
    unsplash: { url: '/test.png?w=200&h=200&fit=fill&fm=jpeg' },
    imagekit: { url: '/test.png?tr=w-200,h-200,cm-pad_resize,f-jpeg' },
    netlify: { url: '/test.png?w=200&h=200&nf_resize=fit' },
    prismic: { url: '/test.png?auto=compress,format&rect=0,0,200,200&w=200&h=200&fit=fill&fm=jpeg' },
    sanity: { url: 'https://cdn.sanity.io/images/projectid/production/test-300x450.png?w=200&h=200&fit=fill&fm=jpg&bg=ffffff' },
    contentful: { url: '/test.png?w=200&h=200&fit=fill&fm=jpg' },
    cloudimage: { url: 'https://demo.cloudimg.io/v7/test.png?width=200&height=200&func=fit&force_format=jpeg' }
  }
] as const

export const modifierFixtures = images.map(image => image.args[1])
