packages:
  - docs
  - example
  - playground

verifyDepsBeforeRun: install

overrides:
  "@nuxt/image": "workspace:*"
  "@nuxt/schema": "4.4.8"
  "@types/node": "^24.13.2"
  vue: "3.5.39"

allowBuilds:
  "@parcel/watcher": false
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
