packages:
  - "docs"
  - "example"
  - "playground"

verifyDepsBeforeRun: install

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
