packages:
  - docs
  - example
  - playground

verifyDepsBeforeRun: install

overrides:
  "@nuxt/image": "workspace:*"
  "@types/node": "^24.13.2"
  vue: "3.5.38"

allowBuilds:
  "@parcel/watcher": false
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false

minimumReleaseAgeExclude:
  - 'nitro-nightly@3.0.1-20260722-224121-77b77ffb'
  - '@nuxt/kit-nightly@5.0.0-29753733.5d6e61e0'
  - '@nuxt/nitro-server-nightly@5.0.0-29753733.5d6e61e0'
  - '@nuxt/schema-nightly@5.0.0-29753733.5d6e61e0'
  - '@nuxt/vite-builder-nightly@5.0.0-29753733.5d6e61e0'
  - nuxt-nightly@5.0.0-29753733.5d6e61e0
