export { cloudinary } from './cloudinary'
export { fastly } from './fastly'
export { imagekit } from './imagekit'
export { imgix } from './imgix'
export { twicpics } from './twicpics'
export { local } from './local'
