name: Release

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  update-changelog:
    if: github.repository_owner == 'nuxt' && !contains(github.event.head_commit.message, 'v1.')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - run: pnpm jiti ./scripts/update-changelog.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
