name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: nuxt/.github/.github/workflows/dependency-review.yml@60bcfda2a9d7abdf79f9832012d26d0a5e548285 # main
    with:
      fail-on-provenance-change: true
