name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: nuxt/.github/.github/workflows/dependency-review.yml@a1146e61cba0e1604a71fcaa574e7642113b127a # main
    with:
      fail-on-provenance-change: true
