name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: nuxt/.github/.github/workflows/dependency-review.yml@a010e7f1f048a853c93fea6198db467e6463ec23 # main
    with:
      fail-on-provenance-change: true
